language: r
sudo: false
cache: packages
warnings_are_errors: false

before_script:
  - curl -X PUT localhost:5984/myapp_test

services:
  - couchdb

after_success:
  - Rscript -e 'covr::codecov()'

notifications:
  email:
    on_success: never
    on_failure: never
