language: r
sudo: required
cache: packages
warnings_are_errors: false

before_install:
  - docker run -p 5984:5984 klaemo/couchdb:2.0-rc2 --with-haproxy

before_script:
  - curl -X PUT localhost:5984/testing123

services:
  - docker

after_success:
  - Rscript -e 'covr::codecov()'

notifications:
  email:
    on_success: never
    on_failure: never

